name: Release

on:
  release:
    types: [ published ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: vimtor/action-zip@v1.2
        with:
          files: custom_components/
          dest: sat.zip